%YAML:1.0

ceiling_grid:
  - tag: 0
    size: 78.7
    translation: [0., 0., 0.]
    keep: false
  - tag: 1
    size: 78.7
    translation: [914.4, 0., 0.]
    keep: false
  - tag: 2
    size: 78.7
    translation: [1828.8, 0., 0.]
    keep: false
  - tag: 3
    size: 78.7
    translation: [2743.2, 0., 0.]
    keep: false
  - tag: 4
    size: 78.7
    translation: [0., 914.4, 0.]
    keep: false
  - tag: 5
    size: 78.7
    translation: [914.4, 914.4, 0.]
    keep: false
  - tag: 6
    size: 78.7
    translation: [1828.8, 914.4, 0.]
    keep: false
  - tag: 7
    size: 78.7
    translation: [2743.2, 914.4, 0.]
    keep: false
  - tag: 8
    size: 78.7
    translation: [0., 1828.8, 0.]
    keep: false
  - tag: 9
    size: 78.7
    translation: [914.4, 1828.8, 0.]
    keep: false
  - tag: 10
    size: 78.7
    translation: [1828.8, 1828.8, 0.]
    keep: false
  - tag: 11
    size: 78.7
    translation: [2743.2, 1828.8, 0.]
    keep: false
  - tag: 12
    size: 78.7
    translation: [0., 2743.2, 0.]
    keep: false
  - tag: 13
    size: 78.7
    translation: [914.4, 2743.2, 0.]
    keep: false
  - tag: 14
    size: 78.7
    translation: [1828.8, 2743.2, 0.]
    keep: false
  - tag: 15
    size: 78.7
    translation: [2743.2, 2743.2, 0.]
    keep: false


