%YAML:1.0

ceiling_grid_razpi:
  - tag: 13
    size: 193.0
    translation: [0., 0., 0.]
    keep: false
  - tag: 14
    size: 193.0
    translation: [914.4, 0., 0.]
    keep: false
  - tag: 15
    size: 193.0
    translation: [1828.8, 0., 0.]
    keep: false
  - tag: 16
    size: 193.0
    translation: [2743.2, 0., 0.]
    keep: false
  - tag: 32
    size: 193.0
    translation: [0., 914.4, 0.]
    keep: false
  - tag: 33
    size: 193.0
    translation: [914.4, 914.4, 0.]
    keep: false
  - tag: 34
    size: 193.0
    translation: [1828.8, 914.4, 0.]
    keep: false
  - tag: 35
    size: 193.0
    translation: [2743.2, 914.4, 0.]
    keep: false
  - tag: 51
    size: 193.0
    translation: [0., 1828.8, 0.]
    keep: false
  - tag: 52
    size: 193.0
    translation: [914.4, 1828.8, 0.]
    keep: false
  - tag: 53
    size: 193.0
    translation: [1828.8, 1828.8, 0.]
    keep: false
  - tag: 54
    size: 193.0
    translation: [2743.2, 1828.8, 0.]
    keep: false
  - tag: 70
    size: 193.0
    translation: [0., 2743.2, 0.]
    keep: false
  - tag: 71
    size: 193.0
    translation: [914.4, 2743.2, 0.]
    keep: false
  - tag: 72
    size: 193.0
    translation: [1828.8, 2743.2, 0.]
    keep: false
  - tag: 73
    size: 193.0
    translation: [2743.2, 2743.2, 0.]
    keep: false


